# This is a basic workflow to help you get started with Actions

name: portlandmaps assessor 

on:
  schedule:
    - cron: "0 0 * * *" # 8 a.m. every day UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - run: pip install notebook numpy pandas requests time
    
    - name: Run scraper
      run: jupyter execute portlandmaps-assessor.ipynb
      
    - name: Add and commit
      id: add_commit
      uses: EndBug/add-and-commit@v8
      with:
        committer_name: Automated
        committer_email: actions@users.noreply.github.com
        message: "Latest data"
